name:                benjibot
version:             0.1.0.0
github:              "githubuser/benjibot"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/benjibot#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  ghc-options:
  - -Wall
  dependencies:
  - tablebot
  - text
  - containers
  - aeson
  - discord-haskell
  - split
  - mtl
  - time
  - transformers
  - raw-strings-qq
  - text-icu
  - text-regex-replace
  - http-conduit
  - yaml
  - megaparsec
  default-extensions:
      OverloadedStrings
      LambdaCase
      EmptyDataDecls
      FlexibleContexts
      GADTs
      GeneralizedNewtypeDeriving
      MultiParamTypeClasses
      QuasiQuotes
      TemplateHaskell
      TypeFamilies
      DerivingStrategies
      StandaloneDeriving
      UndecidableInstances
      DataKinds
      FlexibleInstances
      DeriveGeneric
      TypeApplications
      MultiWayIf
      TupleSections
      ConstraintKinds
      RecordWildCards
      ScopedTypeVariables
      TypeOperators
      RankNTypes
      BangPatterns

executables:
  benjibot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - benjibot
    - tablebot
    - data-default
    - text
    

tests:
  benjibot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - benjibot
